# Generated by Django 5.0.7 on 2024-09-26 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_category_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
