# Generated by Django 5.0.7 on 2024-10-01 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_menu_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('img', models.ImageField(upload_to='static/images/slider/')),
                ('descr', models.TextField(blank=True, null=True)),
                ('position', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='img',
            field=models.ImageField(upload_to='static/images/categorie/'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='img',
            field=models.ImageField(upload_to='static/images/menu/'),
        ),
    ]
