# Generated by Django 5.0.7 on 2024-10-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_slider_alter_category_img_alter_menu_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appconf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='images/logo/')),
                ('img', models.ImageField(upload_to='images/logo/')),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='img',
            field=models.ImageField(upload_to='images/categorie/'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='img',
            field=models.ImageField(upload_to='images/menu/'),
        ),
    ]
