# Generated by Django 5.0.7 on 2024-10-02 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_appconf_alter_category_img_alter_menu_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField()),
                ('story', models.TextField()),
                ('goal', models.TextField()),
            ],
            options={
                'verbose_name': 'Hakkımızda',
                'verbose_name_plural': 'Hakkımızda',
            },
        ),
        migrations.AlterModelOptions(
            name='appconf',
            options={'verbose_name': 'Konfigurasyon', 'verbose_name_plural': 'Site Konfigurasyonu'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kategori', 'verbose_name_plural': 'Kategoriler'},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'Menü', 'verbose_name_plural': 'Menüler'},
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name': 'Slayt', 'verbose_name_plural': 'Slaytlar'},
        ),
    ]
