# Generated by Django 5.0.7 on 2024-10-02 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_about_alter_appconf_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='about',
            new_name='bulletpoint_1',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='goal',
            new_name='bulletpoint_2',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='story',
            new_name='bulletpoint_3',
        ),
    ]
